apiVersion: v1
kind: Service
metadata:
  name: chatapp
spec:
  selector:
    app: chatapp
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: app
          image: yagna32/chat_app_image:v2.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/Chat-App
          imagePullPolicy: Always